type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Google Sheets Query"
      parameters:
        componentName: "Start"
    Google Sheets Query:
      type: "google-sheets-query"
      transitions:
        success:
        - "Assert Table"
      parameters:
        componentName: "Google Sheets Query"
        basicAdvancedMode: "Basic"
        authentication: "Google-Sheets"
        spreadsheetName: "Marketing Lead Data (Gartner MQ)"
        containsHeaderRow: "Yes"
        cellRange:
        connectionOptions:
        dataSource: "Marketing Lead Data (Gartner MQ)_Sheet1"
        dataSelection:
        - "Company Name"
        - "Country"
        - "Date of Inquiry"
        - "Email Address"
        - "First Name"
        - "id"
        - "Interested Products"
        - "Job Title"
        - "Last Name"
        - "Lead ID"
        - "Lead Score"
        - "Phone Number"
        - "Source"
        dataSourceFilter:
        combineFilters: "And"
        limit: ""
        type: "Standard"
        primaryKeys:
        warehouse1: "[Environment Default]"
        database: "[Environment Default]"
        schema: "GARTNER_MQ_2024"
        targetTable: "s_marketing_lead"
        stage1: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
    Assert Table:
      type: "assert-table"
      transitions:
        success:
        - "End Success"
        failure:
        - "End Failure"
      parameters:
        componentName: "Assert Table"
        database: "[Environment Default]"
        schema: "GARTNER_MQ_2024"
        tableName: "s_marketing_lead"
        exists: "Yes"
        tableMetadata:
        rowCountComparisonType: "Equal To"
        rowCountValue:
    End Success:
      type: "end-success"
      parameters:
        componentName: "End Success"
    End Failure:
      type: "end-failure"
      parameters:
        componentName: "End Failure"
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Google Sheets Query:
      position:
        x: 120
        "y": 0
      tempMetlId: 2
    Assert Table:
      position:
        x: 240
        "y": 0
      tempMetlId: 3
    End Success:
      position:
        x: 360
        "y": -110
      tempMetlId: 4
    End Failure:
      position:
        x: 360
        "y": 80
      tempMetlId: 5
